<a href="https://colab.research.google.com/github/I7411/THDeepLearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#3.1 tạo array 1 chiều

In [1]:
pip install numpy

In [2]:
import numpy as np

# cách 1
# tạo list
my_list = [1, 9, 15, 39]
print('Python list:', my_list)
#chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

#cách 2
a = np.array([1, 9, 15, 39])
print(a)



Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


#3.2 array 2 chiều


In [3]:
c = np.array([(1, 2, 3),
              (4, 5, 6)
              ])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


#3.3 array 3 chiều

In [5]:
d = np.array([
    [[1., 2.,3.], [4.,5.,6.]],
    [[7., 8., 9.], [10, 11, 12]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


#3.4 tạo array với giá trị ban đầu là 0 hoặc 1

In [6]:
e = np.zeros((2,2))
f = np.ones((3,3))
print('Zero matrix:\n', e)
print('One matrix\n', f)


Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#3.5 reshape và flatten ma trận


In [7]:
e = np.array([[1.,2.,3.], [4.,5.,6.]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
g = np.array([[[1.,2.,3.], [4.,5.,6.]],
              [[7.,8.,9.], [10.,11.,12.]]
              ])
print(g)
print(g.shape)
h = g.reshape(3,4)
print('reshape (3,4)\n',h)
j = g.reshape(3, 2, 2)
print('reshape (3,2,2)\n', j)
k = g.reshape(2,3,2)
print('reshape (2,3,2)\n',k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


#3.5.2 Platten là chuyển array nhiều chiều về 1 chiều

In [8]:
e = np.array([[1.,2.,3.,], [4.,5.,6.]])
f = e.flatten()
print(f)
g = np.array([[[1.,2.,3.,], [4.,5.,6.]],
              [[7.,8.,9.], [10.,11.,12.]]
              ])
j = g.flatten()
print(j)


[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


#3.6 thêm dòng dữ liệu với hstack và vstack

In [9]:
f = np.array([1.,2.,3.])
g= np.array([4.,5.,6.])
h_stack = np.hstack((f,g))
print('Horizontal Append\n', h_stack)
v_stack = np.vstack((f,g))
print('Vertical Append\n', v_stack)


Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


#3.7 Sinh mảng số ngẫu nhiên

In [10]:
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n',a)
b = np.random.randint(100, size=(3,4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3,4,3))
print('Random 3-D array\n', c)

Random 1-D array
 [86 30 50 85  4]
Random 2-D array
 [[79 40 25 66]
 [55 69  6 30]
 [71 37 63 96]]
Random 3-D array
 [[[74 98 69]
  [53 37 20]
  [11 85 38]
  [23  7 36]]

 [[86 44 26]
  [83 14 25]
  [62  2 53]
  [35 10 93]]

 [[46 42 25]
  [24 47 95]
  [ 2 59 89]
  [47  0 89]]]


#3.7.2. Sinh mảng số thực trong khoảng[0,1]

In [11]:
#sinh ngẫu nhiên mảng số thực [0,1]
a = np.random.rand(5)
print('Random 1-D array\n', a)
b = np.random.rand(3,4)
print('Random 2-D array\n', b)
c =np.random.rand(3,4,3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.97708658 0.54488431 0.24654237 0.82105402 0.81580415]
Random 2-D array
 [[0.58873778 0.81321929 0.14035934 0.57278131]
 [0.30524968 0.04562529 0.50871497 0.57860923]
 [0.61913491 0.39493369 0.96666676 0.60998512]]
Random 3-D array
 [[[0.37140689 0.97442904 0.78216391]
  [0.06973651 0.41463657 0.38018218]
  [0.91528805 0.62756557 0.50162196]
  [0.86216798 0.42312298 0.52836777]]

 [[0.83834046 0.5599728  0.96606735]
  [0.44190148 0.90013049 0.82780506]
  [0.65018461 0.02147283 0.85694639]
  [0.21717428 0.00459509 0.7048199 ]]

 [[0.45032196 0.93992925 0.50161403]
  [0.65346891 0.22336199 0.28160291]
  [0.3262534  0.86544822 0.20324109]
  [0.02658794 0.94277151 0.49679034]]]


#3.7.3 Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gausian

In [12]:
a = np.random.normal(5,0.5,10)
print(a)

[5.74504343 4.37987042 5.24585279 4.95671889 4.50655984 4.2848188
 4.88927489 4.70900437 5.51037658 4.28297285]


#3.7.4 Sinh ngẫu nhiên một giá tị từ mảng giá trị cho trước


In [13]:
#sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)
#sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([2,4,6,8,10,12,14,16,18,20], size=(3,5))
print(b)


4
[[10 10  4  4 10]
 [14 14 12 10 10]
 [18 20  4 16  6]]


# 3.8 thay đổi giá trị của ma trận

In [14]:
#tạo ma trận 5 x 5 với số 1
A = np.matrix(np.ones((5,5)))
print('The matrix\n', A)
np.array(A)[2]=2
print('Change values of third row with array\n', A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#3.9 sinh dãy số theo khoảng cho trước
3.9.1 dùng hàm arange

In [15]:
#tạo 20 số nguyên từ 1 đến (n-1)
a = np.arange(1,20)
print(a)
#tạo 20 số nguyên từ 1 đến (n-1), mỗi bước tăng 2 giá trị
b = np.arange(1,20,2)
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


3.9.2 Dùng hàm linspace

In [16]:
a = np.linspace(1.,5.,num=10)
print(a)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


#3.10 Index và slide


In [17]:
#slide
a = np.array([(1,2,3), (4,5,6)])
print(a)
print('first row:', a[0])
print('second row', a[1])
#indexing
print('Second column:',a[:,1])
print('first column:',a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row [4 5 6]
Second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]
