<a href="https://colab.research.google.com/github/I7411/THDeepLearning/blob/main/TENSORFLOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

#3.1. tensor 0 chieu

In [2]:
#this will be an int32 tensor by default
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)


tf.Tensor(4, shape=(), dtype=int32)


In [3]:
#this will be an int32 tensor by default
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9, tf.int16)
print(r1)
r1_float = tf.constant(1.12, tf.float32)
print(r1_float)
r1_string = tf.constant('Hello HUIT University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello HUIT University', shape=(), dtype=string)


#3.2 Tensor 1 chieu

In [4]:
# We make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)


tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


#3.3 tensor 2 chieu (ma tran)

In [5]:
rank_2_tensor = tf.constant([[1, 2],
[3, 4],
[5, 6]], dtype=tf.float16)

print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


#3.4 tensor n chieu (nhieu ruc)

In [6]:
rank_3_tensor = tf.constant([
[[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9]],
[[10, 11, 12, 13, 14],
[15, 16, 17, 18, 19]],
[[20, 21, 22, 23, 24],
[25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


#3.5. Thuộc tính của tensor

In [7]:
rank_3_tensor = tf.constant([
[[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9]],
[[10, 11, 12, 13, 14],
[15, 16, 17, 18, 19]],
[[20, 21, 22, 23, 24],
[25, 26, 27, 28, 29]],])

print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:',rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


#3.6. Tạo tensor tự động gán giá trị 0 ban đầu

In [8]:
t_zero = tf.zeros(10)
print(t_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [10]:
t_2_zero = tf.zeros([3,3])
print(t_2_zero)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [11]:
t_3_zero = tf.zeros([3,3,5])
print(t_3_zero)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


#3.7. Tạo tensor tự động gán giá trị 1 ban đầu

In [13]:
t_one = tf.ones(10)
print(t_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)


In [ ]:
t_2_one = tf.ones([3,3])
print(t_2_one)

In [14]:
t_3_one = tf.ones([3,3,5])
print(t_3_one)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


#3.8. Tạo tensor tự động với giá trị bất kỳ

In [15]:
t_1 = tf.fill(3,10)
print(t_1)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [16]:
t_2 = tf.fill([3,3], 9)
print(t_1)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


#3.9. Tạo tensor 1-chiều với hàm linspace

In [18]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)


tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


#3.10. Tạo tensor 1-chiều với hàm range


In [19]:
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


In [20]:
range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


#3.11 Tạo tensor với giá trị ngẫu nhiên

In [21]:
range_tersor = tf.random.normal([5])
print(range_tensor)

tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


In [22]:
range_tensor = tf.random.normal([3,3])
print(range_tensor)

tf.Tensor(
[[-0.3077341   1.4696733   0.38216332]
 [ 0.69402254  0.06970005  0.12471845]
 [ 1.5583382  -0.9465689  -0.35841444]], shape=(3, 3), dtype=float32)


In [24]:
range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

tf.Tensor([-0.05978647 -0.16411392 -1.3433956  -0.18213192 -0.4831894 ], shape=(5,), dtype=float32)


In [25]:
range_tensor = tf.random.truncated_normal([3,2])
print(range_tensor)

tf.Tensor(
[[-0.19338013 -1.0018504 ]
 [ 0.66154987  1.0392116 ]
 [ 0.9991076   0.10257313]], shape=(3, 2), dtype=float32)


In [27]:
range_tensor = tf.random.truncated_normal([3,2,2])
print(range_tensor)

tf.Tensor(
[[[-0.8775833  -0.11748955]
  [-0.58121383  1.2940081 ]]

 [[ 0.1484716   1.0926212 ]
  [ 0.18178308 -1.10406   ]]

 [[-1.072557    0.95900303]
  [ 1.2839189  -1.6298621 ]]], shape=(3, 2, 2), dtype=float32)


In [28]:
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

tf.Tensor([13.233962 16.942455 11.48579  17.924618 10.086669], shape=(5,), dtype=float32)


In [29]:
range_tensor = tf.random.uniform([3,2,5], minval=10, maxval=20)
print(range_tensor)

tf.Tensor(
[[[13.208229 18.591152 18.456478 18.041916 18.081888]
  [13.887085 18.986263 14.086908 11.724258 13.758718]]

 [[15.692707 14.119621 18.828854 17.740755 17.98363 ]
  [19.71057  17.009174 11.693815 13.377768 13.427276]]

 [[19.36775  11.718691 19.623262 18.086325 16.40232 ]
  [14.549831 17.363075 11.405687 16.821411 18.6496  ]]], shape=(3, 2, 5), dtype=float32)


In [30]:
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([13.407759 13.988105 19.489574 15.172865 12.664705], shape=(5,), dtype=float32)
tf.Tensor([15.172865 19.489574 13.988105 12.664705 13.407759], shape=(5,), dtype=float32)


#3.12. Chuyển đổi kiểu dữ liệu

In [31]:
t_float = tf.constant(3.9, tf.float32)
print(t_float,' --- ', t_float.dtype)
t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, ' --- ', t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32)  ---  <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32)  ---  <dtype: 'int32'>


#3.13. Các phép toán trong tensorflow

#3.13.1. Tính căn bậc 2 của một tensor scalar

In [32]:
x = tf.constant(2, dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor(1.4142135, shape=(), dtype=float32)


#3.13.2. Cộng 2 tensor

In [33]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.add(a, b)
d = a + b
print(c)
print(d)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


#3.13.3. Nhân 2 tensor


In [34]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.multiply(a, b)
d = a * b
print(c)
print(d)

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


In [36]:
a = tf.constant([6. , 6., 6.])
b = tf.constant([4., 4., 4.])
c = tf.constant([3. , 3. , 3.])
d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

print(i)
print(1)

tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
1


#3.14. Các phép toán làm tròn và so sánh


In [37]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)
print(r4)

tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


#3.15. Các phép toán trên vector và ma trận

In [38]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
[4, 5, 6]])
t4 = tf.constant([[7, 8],
[9, 10],
[11, 12]])
dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)
print(t1)
print(t2)
print(t3)
print(t4)
cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)
print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


#3.16. Biến trong tensorflow

In [39]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
print('Shape', diem.shape)
print('Dtype', diem.dtype)
print('numpy:', diem.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape (2,)
Dtype <dtype: 'int32'>
numpy: [5 9]


In [40]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
diem.assign([8, 10])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>


#3.17. Môi trường tính toán Graph trong tensorflow

In [42]:
import tensorflow as tf

# Define a Python function.
def a_regular_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

# 'a_function_that_uses_a_graph' is a TensorFlow Function.
a_function_that_uses_a_graph = tf.function(a_regular_function)

# Make some tensors.
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
# Call a Function like a Python function.
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()

print(orig_value)
print(tf_function_value)

[[12.]]
[[12.]]


#3.17.1. Biến một hàm Python thuần túy sang graph

In [44]:
def inner_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

# Use the decorator to make `outer_function' a `Function'.
@tf. function
def outer_function(x):
  y = tf.constant([[2.0], [3.0]])
  b = tf.constant(4.0)

  return inner_function(x, y, b)

# Note that the callable will create a graph that
# includes `inner_function' as well as `outer_function'.
rs = outer_function(tf.constant([[1.0, 2.0]])).numpy()
print(rs)

[[12.]]


#3.18. Modules, Layers và Models

In [46]:
import tensorflow as tf

class SimpleModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.a_variable = tf.Variable(5.0, name="train_me")
        self.non_trainable_variable = tf.Variable(
            5.0, trainable=False, name="do_not_train_me"
        )

    def __call__(self, x):
        return self.a_variable * x + self.non_trainable_variable

simple_module = SimpleModule(name="simple")

rs = simple_module(tf.constant(5.0))
print(rs)
print('Train variables:', simple_module.trainable_variables)
print('All variables:', simple_module.variables)

tf.Tensor(30.0, shape=(), dtype=float32)
Train variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)


In [47]:
import tensorflow as tf

class Dense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([in_features, out_features]), name='w'
        )
        self.b = tf.Variable(
            tf.zeros([out_features]), name='b'
        )

    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

class SequentialModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

        self.dense_1 = Dense(in_features=3, out_features=3)
        self.dense_2 = Dense(in_features=3, out_features=2)

    def __call__(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)

# You have made a model!
my_model = SequentialModule(name="the_model")

# Call it, with random results
print("Model results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))

Model results: tf.Tensor([[0.8183307 1.9928955]], shape=(1, 2), dtype=float32)


#3.19. Lưu weight


#3.19.1.  Lưu checkpoint


In [48]:
chkp_path = "my_checkpoint"
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write(chkp_path)

'my_checkpoint'

#3.19.2.  Phục hồi checkpoint

In [50]:
new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint")

# Should be the same result as above
print(new_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor([[0.8183307 1.9928955]], shape=(1, 2), dtype=float32)
